### ISSUE TITLE
[Issue] COCO-Stuff-164K dataset

### ISSUE THREAD

**Issue by ZaberKo** [winycg/CIRKD#27]
I found the `CocoStuff164kTrainSet.num_class` is mistakenly set to 182, where some class id is missing in the dataset. Commonly, the num_class is set to 171 with a class_id map as suggested in [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/main/tools/dataset_converters/coco_stuff164k.py). So is it a intended design or just a typo?

**Comment by winycg** [comment]
Thank you for pointing out this problem. I have fixed this problem.

**Comment by ZaberKo** [comment]
> Thank you for pointing out this problem. I have fixed this problem.

It seems that the fix is still incorrect. The category_id should be remapped. I have submitted a PR (#28) to fix it, based on the convertion script in mmseg, so we do not have to change a lot of codes.

**Comment by winycg** [comment]
Hi, thanks for your suggestions! In this codebase, I use coco-stuff-164k with 182 classes to provide pre-trained models, following "To be compatible with COCO, COCO-Stuff has 91 thing classes (1-91), 91 stuff classes (92-182) and 1 class "unlabeled" (0). Note that 11 of the thing classes of COCO do not have any segmentation annotations (blender, desk, door, eye glasses, hair brush, hat, mirror, plate, shoe, street sign, window). " in the official codebase [https://github.com/nightrome/cocostuff](url). I will remap the label id and retrain the models.
